# .streamlit/secrets.toml
###使用者、管理者
[passwords]
# Follow the rule: username = "password"
user1 = "midplatform@123"
user2 = "midplatform@456"
user3 = "midplatform@789"
user4 = "midplatform@qwe"
user5 = "midplatform@asd"
user6 = "midplatform@zxc"
user7 = "midplatform@abc"
user8 = "midplatform@xyz"
user9 = "midplatform@010"
user10 = "midplatform@315"

admin1 = "midplatform@123"
admin2 = "midplatform@456"
admin3 = "midplatform@789"
admin4 = "midplatform@qwe"
admin5 = "midplatform@asd"
admin6 = "midplatform@zxc"
admin7 = "midplatform@abc"
admin8 = "midplatform@xyz"
admin9 = "midplatform@010"
admin10 = "midplatform@315"


1 = "1"

